name: run

on:
  push:
    branche:
        - main
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            with: 
              node-version: 20
            - run: home.html
              
            
    
        
    
